apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv
  namespace: testzzw
  labels:
    pv: zookeeper-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /testzzw/zookeeper/conf
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-pvc
  namespace: testzzw
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv: zookeeper-pv