apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
  namespace: testzzw
  labels:
    pv: kafka-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /testzzw/kafka/conf
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc
  namespace: testzzw
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv: kafka-pv